---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  annotations:
    gitHubOrg: cze-dk
    gitHubRepo: compass-demo-repo
  name: compass-demo-repo
spec:
  id: compass-demo-repo
  compositionSelector:
    matchLabels:
      type: aws
      location: local
  parameters:
    namespace: infra
    image: docker.io/vfarcic/compass-demo-repo:latest
    port: 8080
    host: compass-demo-repo.acme.com
    db:
      version: "14"
      size: small
